#!/usr/bin/env node --max-old-space-size 8192
'use strict';
const program = require('commander');

program
    .version('0.1.2', '-v, --version')
    .usage('[command]')
    .command('run', 'Run a GeneNoteBook server')
    .command('add [type]', 'Add data to a running GeneNoteBook server')
    .command('remove [type]', 'Remove data from a running GeneNoteBook server')
    .command('list', 'List contents of a running GeneNoteBook server')
    .parse(process.argv);
