#!/usr/bin/env node
/* eslint-disable no-underscore-dangle, no-console */

const program = require('commander');
const pkginfo = require('./package.json');

program
  .version(pkginfo.version, '-v, --version')
  .usage('[command]')
  .command('run', 'Run a GeneNoteBook server')
  .command('add [type]', 'Add data to a running GeneNoteBook server')
  .command('remove [type]', 'Remove data from a running GeneNoteBook server')
  .command('list', 'List contents of a running GeneNoteBook server');

program.on('command:*', function([command]) {
  if (this._execs[command]) return;
  console.warn(`Unkown genenotebook command: ${command}`);
  program.help();
});

program.parse(process.argv);
